name: walletapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
  - family: Custom
    fonts:
    - asset : asset/font/Custom.ttf
  - family : OCR A Extended
    fonts :
    - asset : asset/font/OCRAEXT.TTF

  assets:
  - asset/images/logo_1.png
  - asset/images/logo_2.png


